name: Coverage

on:
  workflow_run:
    workflows: ["Quality"]
    types:
      - completed

jobs:
  pytest:
    name: Test - pytest
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Berlin"
        needs: pylint.result == 'success'
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install pytest-md
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          job-summary: true
